[package]
name = "vulkan-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.25.0"
image = "0.23.14"
ash = "0.32.1"
ash-window = "0.6.0"
log = "0.4.14"

